
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { GuardadosProvider } from "@/context/GuardadosContext";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-times antialiased`}
        suppressHydrationWarning>
        <GuardadosProvider>
          <Header />
          {children}
          <Footer />
        </GuardadosProvider>
      </body>
    </html>
  );
}
